module.exports = {
  client: {
    service: {
      name: "opensea-graphql",
      // Use local schema file generated by graphql-codegen
      localSchemaFile: "./src/__generated__/graphql.schema.json",
    },
    includes: ["src/**/*.{ts,tsx}"],
    excludes: ["**/__tests__/**", "**/node_modules/**", "**/*.generated.ts"],
  },
}
